init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "6"

platform:
  - x64
#  - x86

shallow_clone: true

install:
  - ps: "Install-windowsfeature -name AD-Domain-Services;
         $password = ConvertTo-SecureString -String \"YX6oio7nHH+a)X1\" -AsPlainText -Force;
         Install-ADDSForest â€“DomainName mycompany.local -SafeModeAdministratorPassword $password;"

build_script:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - npm test

deploy: off
